---

title: "Practica Swirl"
author: "Lucas"
date: "2025-11-06"
=======
output: html_document
---


```{r}
install.packages("swirl")

library(swirl)
swirl()
library(tidyverse)
options(scipen=999) #elimina notacion cientifica
library(readxl)
library(readr)


```


```{r}
enigh <- read.csv("hogares_enigh.csv")
enigh_corto <- select(enigh, folioviv, foliohog,
ing_cor,gasto_mon, tot_integ,
ubica_geo, sexo_jefe, clase_hog,edad_jefe)
enigh_corto <- mutate(enigh_corto, lingreso=log(ing_cor),
lgasto=log(gasto_mon),
gasto_porcentaje=(gasto_mon/ing_cor)*100 )
enigh_corto <- mutate(enigh_corto, ingreso_capita=ing_cor/tot_integ )
enigh_corto <- mutate(enigh_corto, cve_ent=substr(ubica_geo,1,2) )


```

```{r}
hogares_fil <- filter(enigh_corto, ing_cor >0, gasto_mon > 0) %>% group_by(cve_ent, clase_hog) %>% summarise(mean(ingreso_capita), clase_hog = n())   
```

```{r}
 enigh_corto %>%  
  group_by(tot_integ) %>% 
  summarise(conteo = n())
```

```{r}
ingreso  <- enigh %>% filter(ing_cor < 1000000)

ggplot(ingreso)+
  geom_histogram(mapping =aes(x=ing_cor), binwidth=1000)
```

```{r}
ingreso  <- enigh %>% filter(ing_cor < 200000)
ggplot(ingreso)+
  geom_histogram(mapping =aes(x=ing_cor), binwidth=1000)


```

```{r}
ingreso$clase_hog <- gsub(1, "Unipersonal", ingreso$clase_hog)
ingreso$clase_hog <- gsub(2, "Nuclear", ingreso$clase_hog)
ingreso$clase_hog <- gsub(3, "Ampliado", ingreso$clase_hog)
ingreso$clase_hog <- gsub(4, "Compuesto", ingreso$clase_hog)
ingreso$clase_hog <- gsub(5, "Corresidente", ingreso$clase_hog)

```

```{r}
h1<- ggplot(data = ingreso, mapping = aes(x = ing_cor, color = clase_hog)) +
geom_histogram(binwidth = 1000)
h1

```

```{r}
h2<- ggplot(data = ingreso, mapping = aes(x = ing_cor, color = clase_hog)) +
geom_freqpoly(binwidth = 1000)
h2
```

```{r}
h3 <-ggplot(enigh)+
  geom_histogram(mapping =aes(x=ingtrab), binwidth=1000)
h3
```

```{r}
h4 <- ggplot(enigh)+
  geom_histogram(mapping = aes(x=ingtrab), binwidth = 1000)+
  coord_cartesian(xlim = c(0,150000))
h4
```

```{r}
ingresos_trabajo <- enigh %>%
  filter(ingtrab > 0 & ingtrab <= 150000 )

```

```{r}
ggplot(ingresos_trabajo)+
  geom_histogram(mapping = aes(x=ingtrab), binwidth = 1000)
```

```{r}
ggplot(ingresos_trabajo)+
  geom_histogram(mapping = aes(x=ingtrab), binwidth = 10000)
```

```{r}
ggplot(data = ingreso, mapping = aes(x = ing_cor, color = sexo_jefe, group = sexo_jefe)) +
geom_freqpoly(binwidth = 1000)
```
```{r}
ingresos_trabajo$sexo_jefe <- gsub(1, "Masculino", ingresos_trabajo$sexo_jefe)
ingresos_trabajo$sexo_jefe <- gsub(2, "Femenino", ingresos_trabajo$sexo_jefe)

ggplot(data = ingresos_trabajo, mapping = aes(x = ingtrab, color = sexo_jefe)) +
geom_freqpoly(binwidth = 1000)

```

```{r}
summary(enigh$ing_cor)

```

```{r}
enigh <- enigh %>%
mutate(ing_cor = ifelse(ing_cor==0 | ing_cor>200000 , NA, ing_cor))
summary(enigh$ing_cor)
```
```{r}
ggplot(data = enigh, mapping = aes(x = edad_jefe, y = ing_cor )) +
geom_point()

```


```{r}
enigh <- enigh %>%
mutate(ingreso_per_capita = ing_cor/tot_integ )

```


```{r}
ggplot(data = enigh, mapping = aes(x = edad_jefe, y = ing_cor)) +
geom_point(na.rm = TRUE)
```

```{r}

enigh$sexo_jefe<-gsub(1,"Hombre", enigh$sexo_jefe)
enigh$sexo_jefe<-gsub(2,"Mujer", enigh$sexo_jefe)
enigh$clase_hog<-gsub(1, "Unipersonal", enigh$clase_hog)
enigh$clase_hog<-gsub(2, "Nuclear", enigh$clase_hog)
enigh$clase_hog<-gsub(3, "Ampliado", enigh$clase_hog)
enigh$clase_hog<-gsub(4, "Compuesto", enigh$clase_hog)
enigh$clase_hog<-gsub(5, "Corresidente", enigh$clase_hog)
```



```{r}
ggplot(data = na.omit(enigh), mapping = aes(x = clase_hog, y = ingreso_per_capita)) +
geom_boxplot()
```

```{r}
enigh <- enigh %>%
mutate(ingreso_per_capita = ing_cor/tot_integ )

```





```{r}
summarise ( group_by(na.omit(enigh), clase_hog),
mean(ingreso_per_capita), max(ingreso_per_capita), min(ingreso_per_capita),
.groups = "drop")
```


```{r}
enigh2 <- prueba %>%
mutate(educa_jefe =
ifelse(educa_jefe=="1" , "Sin instrucción" ,
ifelse(educa_jefe=="2","Preescolar" ,
ifelse(educa_jefe=="3","Primaria incompleta" ,
ifelse(educa_jefe=="4", "Primaria completa" ,
ifelse(educa_jefe=="5","Secundaria incompleta" ,
ifelse(educa_jefe=="6", "Secundaria completa" ,
ifelse(educa_jefe=="7", "Preparatoria incompleta" ,
ifelse(educa_jefe=="8", "Preparatoria completa" ,
ifelse(educa_jefe=="9", "Profesional incompleta" ,
ifelse(educa_jefe=="10", "Profesional completa" , "Posgrado"
)))))))))))
```

```{r}
ggplot(data = enigh) +
geom_count(mapping = aes(x = clase_hog, y = educa_jefe))
```

```{r}
enigh2 %>%
count(educa_jefe, clase_hog)
```

```{r}
enigh2 %>%
count(educa_jefe , clase_hog) %>%
ggplot(mapping = aes(x = clase_hog , y = educa_jefe)) +
geom_tile(mapping = aes(fill = n))
```

```{r}

enigh %>% 
  count(educa_jefe, sexo_jefe)%>%
  ggplot(mapping = aes(x = sexo_jefe , y = educa_jefe)) +
geom_tile(mapping = aes(fill = n))
```

```{r}
enigh_ej <- enigh %>%
  filter(edad_jefe < 30 & clase_hog == "Unipersonal")
```

```{r}

enigh_ej3 <- enigh_ej %>% 
  select(ubica_geo, edad_jefe, tot_integ, gasto_mon, alimentos, vesti_calz, vivienda, limpieza, salud, transporte, educa_espa, personales, transf_gas)%>%
  mutate (across(c(alimentos:transf_gas),
                 ~ case_when(
                     is.na(gasto_mon) ~ NA_real_,
                     gasto_mon == 0 ~ NA_real_, 
                     TRUE ~ round((./gasto_mon)*100,2)
                     ),
                  .names = "{.col}_pct") )


  
  

```

```{r}
ggplot(data = enigh_ej3, mapping = aes(x = edad_jefe, y = salud )) +
geom_col()


```

```{r}
ggplot(data = enigh_ej3)+
  geom_col(mapping = aes(x = edad_jefe, y = salud ))
```

```{r}
ggplot(data = enigh_ej3)+
  geom_col(mapping = aes(x = edad_jefe, y = salud )) + coord_flip()
```

```{r}
enigh_ejf <- enigh_ej3 %>% 
  na.omit() %>%
  group_by(ubica_geo)%>%
  summarise(mean(salud), round(mean(salud_pct),2), mean(gasto_mon), .groups = "drop")

```

```{r}
read_csv("1,40,5000
2, 25, 2300
1, 15, 4600", col_names=c("sexo","edad","ingreso"))
```

```{r}
enoe <- read.csv("mu_enoe2.csv", col.names = c("Sexo", "Edad", "Ingreso"))



```


```{r}

tabla_1 <- read_excel("tablas_ejemplo.xls", sheet = "tabla1")
tabla_2 <-read_excel("tablas_ejemplo.xls", sheet = "tabla2")
tabla_3 <-read_excel("tablas_ejemplo.xls", sheet = "tabla3")

datos_bm2 <-  read.csv("datos_banco_mundial.csv")
```

```{r}
datos <- datos_bm2%>%
gather(`X1960` : `X2020`, key="periodo", value = "valores")
dim(datos)

datos <- datos %>%
select(-(`serie.Code`)) %>%
spread(key = "serie.Name", value="valores")
dim(datos)
```
```{r}
datos <- datos %>%
mutate(`Cajeros automaticos (por cada 100.000 adultos)` = ifelse
(`Cajeros automaticos (por cada 100.000 adultos)`==".." , NA,
`Cajeros automaticos (por cada 100.000 adultos)`) ) %>%
mutate(`PIB (US$ a precios constantes de 2010)` = ifelse
(`PIB (US$ a precios constantes de 2010)`==".." , NA,
`PIB (US$ a precios constantes de 2010)`) ) %>%
mutate(`Poblacion, total` = ifelse
(`Poblacion, total`==".." , NA,
`Poblacion, total`) )

datos <- datos %>% 
  mutate(`Cajeros automaticos (por cada 100.000 adultos)`=as.numeric(`Cajeros automaticos (por cada 100.000 adultos)`)) %>%
  mutate(`PIB (US$ a precios constantes de 2010)`= as.numeric(`PIB (US$ a precios constantes de 2010)`))%>%
  mutate(`PIB (US$ a precios constantes de 2010)` =as.numeric(`PIB (US$ a precios constantes de 2010)`))

```

```{r}
ggplot(datos, aes(x = periodo, y=`PIB (US$ a precios constantes de 2010)`))+
  geom_line (aes(group = Pais), color= "grey50", na.rm = TRUE) +
  geom_point(aes(color = Pais), na.rm = TRUE)


```
```{r}
library(haven)
library(tidyverse)
hogares <- read_dta("hog_jal.dta")
viviendas <- read_dta("viv_jal.dta")
personas <- read_dta("per_jal.dta")
trabajos <- read_dta("trab_jal.dta")
ingresos <- read_dta("ing_jal.dta")
```

```{r}
plan_rp2 <- hogares %>% 
  semi_join( viviendas %>%
               filter(disp_elect==5), by="folioviv")


```

```{r}
plan_rp3 <- personas %>% 
  semi_join(
    viviendas %>% filter(est_socio == 1),
    by = "folioviv"
  ) %>%
  count(sexo)

```

#Determina en promedio cuanto gastan en salud los hogares cuya vivienda se ubica en vecindad.
```{r}
plan_rp4 <- hogares %>% 
  semi_join(
    viviendas %>% filter(tipo_viv == 3),
    by = "folioviv"
  ) %>%
  mean(salud)

```

#4. Determina el promedio de gasto en educación y esparcimiento (edu_espa) de los hogares, donde todos sus personas saben leer y escribir (alfabetism=1)

```{r}
 plan_rp5 <- hogares %>% 
  semi_join(
    personas %>%  group_by(foliohog) %>%
      filter(alfabetism == 1), by = "foliohog"
  ) %>%
  summarise(todos_alfabetizados = all(educa_espa==1))

plan_rp5 <- hogares %>% 
  semi_join(
    personas %>% 
      group_by(folioviv) %>%
      summarise(todos_alfabetizados = all(alfabetism == 1)) %>%
      filter(todos_alfabetizados),
    by = "folioviv"
  ) %>%
  summarise(promedio_educa_espa = mean(educa_espa, na.rm = TRUE))

```
```{r}

```

```{r}
write.csv(hogares, "t_hogares.csv", row.names = FALSE)
write.csv(viviendas, "t_viviendas.csv", row.names = FALSE)
write.csv(ingresos, "t_ingresos.csv", row.names = FALSE)
write.csv(trabajos, "t_trabajos.csv", row.names = FALSE)
write.csv(personas, "t_personas.csv", row.names = FALSE)

```

